import React from 'react';

const Privacy = () => {
    return (
        <div className="container mx-auto p-4">
            <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
            <p className="mb-2 underline">Last updated: February 2025</p>
            <p className="mb-4">
                Welcome to our Privacy Policy page! When you use our web site services, you trust us with your information. This Privacy Policy is meant to help you understand what data we collect, why we collect it, and what we do with it. This is important; we hope you will take time to read it carefully. Remember, you can find controls to manage your information and protect your privacy and security. We’ve tried to keep it as simple as possible.
            </p>
            <h2 className="text-2xl font-semibold mb-2">Information We Collect</h2>
            <p className="mb-4">
                We collect information to provide better services to all our users – from figuring out basic stuff like which language you speak, to more complex things like which ads you’ll find most useful, the people who matter most to you online, or which YouTube videos you might like.
            </p>
            <h2 className="text-2xl font-semibold mb-2">How We Use Information We Collect</h2>
            <p className="mb-4">
                We use the information we collect from all of our services to provide, maintain, protect and improve them, to develop new ones, and to protect our users. We also use this information to offer you tailored content – like giving you more relevant search results and ads.
            </p>
            <h2 className="text-2xl font-semibold mb-2">Transparency and Choice</h2>
            <p className="mb-4">
                People have different privacy concerns. Our goal is to be clear about what information we collect, so that you can make meaningful choices about how it is used. For example, you can:
            </p>
            <ul className="list-disc list-inside mb-4">
                <li>Review and update your Google activity controls to decide what types of data you would like saved with your account when you use Google services.</li>
                <li>Review and control certain types of information tied to your Google Account by using Google Dashboard.</li>
                <li>View and edit your preferences about the Google ads shown to you on Google and across the web, such as which categories might interest you, using Ads Settings.</li>
                <li>Adjust how the Profile associated with your Google Account appears to others.</li>
            </ul>
            <p className="mb-4">
                You may also set your browser to block all cookies, including cookies associated with our services, or to indicate when a cookie is being set by us. However, it’s important to remember that many of our services may not function properly if your cookies are disabled. For example, we may not remember your language preferences.
            </p>

            <h2 className="text-2xl font-semibold mb-2 text-center m-10">This is a random Privacy Policy Generated by AI 🙂</h2>
        </div>
    );
};

export default Privacy;